@startuml
class Main #grey
package client {
    class Renderer
    class InputHandler
    class GameWindow #red {
        REMOVED
    }
    abstract class AbstractGameScreen #grey
    class MenuScreen #grey extends AbstractGameScreen
    class GameScreen extends AbstractGameScreen {
        (Formerly Game)
    }
    class PauseScreen #grey extends AbstractGameScreen
    class EndScreen #grey extends AbstractGameScreen
}

package entities {
    class GameMap
    class UI
    abstract class Entity
    abstract class ForegroundEntity #grey extends Entity
    class Cell extends Entity
    abstract class Obstacle #grey extends ForegroundEntity
    class Water #grey extends Obstacle
    abstract class Button #grey extends Entity
    class BuildingPlaceButton extends Button
    class PauseButton extends Button
    abstract class Building extends ForegroundEntity
    class Gym extends Building
    class HallsAccommodation extends Building
    class LectureHall extends Building
    class Pub extends Building
    class Restaurant extends Building
}

package server #grey {
    class Server
    package Simulation #grey {
        class Simulation
    }
    package EventHandler #grey {
        class EventHandler
        abstract class Event
        class ExampleEvent extends Event
    }
}

package customs #grey {
    class border
    class leaderboard
}

Main --down[#blue]> Server
Main --down[#blue]> GameScreen
Main --down[#blue]> MenuScreen
Main --down[#blue]> PauseScreen
Main --down[#blue]> EndScreen
EndScreen --down[#blue]> leaderboard
MenuScreen --down[#blue]> leaderboard
GameScreen --left[#blue]> GameMap
GameScreen --left[#blue]> UI
GameScreen --down[#blue]> border
border --left[#blue,thickness=4]> server
server --right[#blue,thickness=4]> border
client --left[#blue,thickness=4]> border
border --right[#blue,thickness=4]> client
entities --left[#blue,thickness=8]> InputHandler
entities --left[#blue,thickness=8]> Renderer
GameMap --[#blue]> Cell
GameMap --[#blue]> Building
GameMap --[#blue]> Obstacle
UI --[#blue]> BuildingPlaceButton
UI --[#blue]> PauseButton
Server --[#blue]> Simulation
Server --[#blue]> EventHandler
EventHandler --[#blue]> ExampleEvent
@enduml
